spring:
  # 使用哪个配置dev
  profiles:
    active: dev
  messages:
    # 指定配置文件的路径默认messages
    basename: i18n.messages

mybatis:
  type-aliases-package: com.zero.domain
  #classpath指的是classes文件夹
  mapper-locations: classpath:mapper/*.xml
  #匹配headerUrl ==header_url
  map-underscore-to-camel-case: true
comment.avatar: /img/log.png
message.avatar: /img/log.png

