spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/share_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 3308
logging:
  level:
    root: info
# 生产环境端口号
server:
  port: 8081